### ISSUE TITLE
wrong shared folder after setup

### ISSUE THREAD

**Issue by enkows** [Unitech/pm2-deploy#19] opened 2014-09-24 16:43 UTC
After run `pm2 deploy env setup`, it makes wrong shared folder like this:

```
|-- myapp
    |-- {shared
        |-- {logs,pids},source}
```

Ubuntu 14.04.1 LTS
Node v0.10.32
pm2 0.10.8

**Comment by mchicote** [comment] 2015-02-02 20:59
Same here.
I was expecting the following folders:
````
/myapp/shared
/myapp/shared/logs
/myapp/shared/pids
/myapp/source
````

**Comment by mchicote** [comment] 2015-02-08 20:49
@Unitech I think this was caused by using `sh` instead of `bash`

**Comment by roderik** [comment] 2016-12-22 15:19
I'm experiencing the same issue. The user i'm deploying with has a shell of bash.

**Comment by membrive** [comment] 2017-12-19 15:17
Same problem here. I am using Ubuntu 14.04, Node.js v8.9.3 and PM2 2.9.1.

**Comment by phra** [comment] 2017-12-31 01:47
@membrive did you check @marcoschicote comment?

**Comment by membrive** [comment] 2018-01-01 19:24
@phra yes, sorry for the delay. Using `bash` solves the problem.

**Comment by phra** [comment] 2018-01-04 20:09
ok, so closing this.

**Closed by phra** 2018-01-04 20:09 UTC

**Comment by luffs** [comment] 2018-11-01 12:03
I ran into this problem and solved it by changing the default shell for my deploy user on the target server with `chsh -s /bin/bash <username>`
